[phases.setup]
nixPkgs = [
  "php83",
  "php83Extensions.sockets",
  "php83Extensions.intl",
  "php83Extensions.gd",
  "php83Extensions.redis",
  "php83Extensions.tidy",
  "php83Extensions.mbstring",
  "php83Extensions.curl",
  "php83Extensions.xml",
  "php83Extensions.simplexml",
  "php83Extensions.dom",
  "php83Extensions.pdo"
]
